// import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
plugins {
    id "java"
    // id "org.jetbrains.kotlin:kotlin-gradle-plugin" version '1.9.21'
//    id "org.jetbrains.intellij" version "1.17.4"
    id "org.jetbrains.intellij.platform" version "2.3.0"
}

group = 'me.jaffe2718'
version = rootProject.version

repositories {
    mavenCentral()

    intellijPlatform {
        defaultRepositories()
        jetbrainsRuntime()
    }
}

sourceSets {
    main {
        java {
            srcDir 'src/main/gen'
        }
    }
}


dependencies {
    implementation 'net.lingala.zip4j:zip4j:2.11.5'

    intellijPlatform {
        intellijIdeaCommunity project.properties['intellij_version']
        bundledPlugin 'com.intellij.java'
        bundledPlugin 'com.intellij.modules.json'
    }
}

intellijPlatform {
    pluginConfiguration {
        id = 'me.jaffe2718.devkit'
        name = 'Minecraft Command DevKit'
        version = project.getProperty('plugin_version')

        ideaVersion {
            sinceBuild = project.properties['idea_since_build']
            untilBuild = project.properties['idea_until_build']
        }

        vendor {
            name = 'Jaffe2718'
            email = 'qqyttwqeei@163.com'
            url = 'https://github.com/Jaffe2718'
        }
    }
}